
networks:
  projectservnet:
    driver: bridge

services:
  app:
    container_name: projectserv
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    depends_on: 
      - postgres
    networks:
      - projectservnet
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=projectservdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - projectservnet
volumes:
  postgres-data:
  
